-- CREATE TYPE e_medium_category AS ENUM(
--     'audio',
--     'video'
-- );

-- CREATE TYPE e_medium_status AS ENUM(
--     'waiting',
--     'in_progress',
--     'success',
--     'failure'
-- );

-- CREATE TABLE IF NOT EXISTS media (
--     id UUID NOT NULL,
--     name TEXT NOT NULL,
--     url TEXT NOT NULL,
--     category e_medium_category NOT NULL,
--     status e_medium_status NOT NULL,
--     created_at timestamp with time zone NOT NULL,
--     updated_at timestamp with time zone NOT NULL,
--     PRIMARY KEY(id)
-- )